WebStoreApp/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreApp.Models;

namespace WebStoreApp.Controllers
{
    public class MenuController : Controller
    {
        private List<MenuItem> _items;

        public MenuController()
        {
            _items = new List<MenuItem>
            {
                new MenuItem
                {
                    Name = "Products",
                    Controller = "Products",
                    Action = "Index",
                    Active = string.Empty
                },
                new MenuItem
                {
                    Name = "Orders",
                    Controller = "Orders",
                    Action = "Index",
                    Active = string.Empty
                }
            };
        }

        public PartialViewResult Main(string controller = "Home")
        {
            var item = _items.FirstOrDefault(i => i.Controller == controller);

            if (item != null)
                item.Active = "active";

            return PartialView(_items);
        }
    }
}

WebStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Web Store App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("News", "News", "Home")</li>
                    <li>@Html.ActionLink("About us", "About", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <!-- Left menu bar -->
    <div class="col-md-2">
        <br />
        <div class="col-md-8 col-md-offset-2">
            @Html.Action("Main", "Menu", new { controller = Request.RequestContext.RouteData.Values["controller"] })
        </div>
    </div>
    <!---->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <h5>
                <label>
                    Moroz Nikita, @DateTime.Now.Year
                </label>
            </h5>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>