WebStoreApp/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebStoreApp.Models
{
    public class Order
    {
        public Order()
        {
            OrdersProducts = new List<OrdersProducts>();
        }

        public int Id { get; set; }

        public DateTime DateBought { get; set; }

        [ForeignKey("User")]
        [Required]
        public string UserId { get; set; }

        // navigation properties
        public virtual List<OrdersProducts> OrdersProducts { get; set; }
        public virtual AspNetUser User { get; set; }
    }
}

WebStoreApp/ViewModels/OrderViewModel.cs
using System;
using WebStoreApp.Models;

namespace WebStoreApp.ViewModels
{
    public class OrderViewModel
    {
        public int Id { get; set; }

        public DateTime DateBought { get; set; }

        public double Price { get; set; }

        public OrderViewModel()
        { }

        public OrderViewModel(Order order)
        {
            Id = order.Id;
            DateBought = order.DateBought;
        }
    }
}

WebStoreApp/ViewModels/PeriodInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebStoreApp.ViewModels
{
    public class PeriodInfoViewModel
    {
        [Display(Name = "Sales")]
        public int SalesNumber { get; set; }

        [Display(Name = "Total price")]
        public double Price { get; set; }
    }
}

WebStoreApp/ViewModels/PeriodViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebStoreApp.ViewModels
{
    public class PeriodViewModel
    {
        [Required(ErrorMessage = "Enter the Start Date")]
        [Display(Name = "Start Date")]
        public DateTime? StartDate { get; set; }

        [Required(ErrorMessage = "Enter the End Date")]
        [Display(Name = "End Date")]
        public DateTime? EndDate { get; set; }
    }
}

WebStoreApp/ViewModels/UserOrderInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebStoreApp.Models;
using WebStoreApp.Customs;

namespace WebStoreApp.ViewModels
{
    public class UserOrderInfoViewModel
    {
        public List<OrderInfo> Orders { get; set; }

        public double TotalPrice { get; set; }
    }
}

WebStoreApp/ViewModels/UserOrderViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebStoreApp.Models;

namespace WebStoreApp.ViewModels
{
    public class UserOrderViewModel
    {
        [Display(Name = "AspNetUser")]
        public string UserId { get; set; }

        public List<AspNetUser> Users { get; set; }
    }
}

WebStoreApp/Controllers/OrdersController.cs
using System;
using System.Security.Claims;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreApp.Models;
using WebStoreApp.ViewModels;
using WebStoreApp.Customs;
using Microsoft.AspNet.Identity;
using System.Threading;

namespace WebStoreApp.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        ApplicationContext _context;

        public OrdersController()
        {
            _context = new ApplicationContext();
        }

        // GET: Orders
        public ActionResult Index()
        {
            List<OrderViewModel> model = new List<OrderViewModel>();

            foreach (var order in _context.Orders.ToList())
            {
                var userId = User.Identity.GetUserId();
                if (order.UserId == userId)
                {
                    var viewModel = new OrderViewModel(order);
                    viewModel.Price = CountOrderPrice(order);

                    model.Add(viewModel);
                }
            }

            return View(model);
        }

        public ViewResult Add()
        { 
            return View(PrepareOrderFormViewModel());
        }

        //[ValidateAntiForgeryToken]
        public ActionResult Save(OrderFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("Add", viewModel);

            // get user
            var userFromDb = _context.Users.Find(User.Identity.GetUserId());
            if (userFromDb == null)
                return HttpNotFound();

            // create order
            var order = new Order
            {
                DateBought = viewModel.DateBought ?? DateTime.Now
            };
            userFromDb.Orders.Add(order);

            // add products with ammounts
            bool isProductChosen = false;
            foreach (var item in viewModel.ProductsAmmount)
            {
                if (item.Ammount != 0)
                {
                    var productFromDb = _context.Products.SingleOrDefault(p => p.Id == item.ProductId);
                    if (productFromDb == null)
                        return HttpNotFound();

                    order.OrdersProducts.Add(new OrdersProducts
                        {
                            Product = productFromDb,
                            ProductAmmount = item.Ammount
                        }
                    );

                    isProductChosen = true;
                }
            }

            if (!isProductChosen)
            {
                ModelState.AddModelError("", "You should choose at least one product");
                return View("Add", PrepareOrderFormViewModel());
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ViewResult Period()
        {
            return View(new PeriodViewModel());
        }

        public PartialViewResult GetPeriodInfo(PeriodViewModel viewModel)
        {
            var orders = _context.Orders.Where(o => 
                                            o.DateBought >= viewModel.StartDate 
                                            && o.DateBought <= viewModel.EndDate
                                            )
                                            .ToList();

            double totalPrice = 0;
            foreach (var order in orders)
            {
                totalPrice += CountOrderPrice(order);
            }

            return PartialView("_PeriodInfo", new PeriodInfoViewModel { SalesNumber = orders.Count, Price = totalPrice });
        }

        //public ViewResult UserOrder()
        //{
        //    var viewModel = new UserOrderViewModel()
        //    {
        //        Users = _context.Users.OrderBy(u => u.FullName).ToList()
        //    };

        //    return View(viewModel);

        //}

        //public PartialViewResult GetUserOrderInfo()
        //{
        //    // get User's orders
        //    var userId = User.Identity.GetUserId();
        //    var orders = _context.Orders.Where(o => o.UserId == userId).ToList();

        //    if (orders == null || orders.Count == 0)
        //    {
        //        return PartialView("_UserOrderInfo", null);
        //    }

        //    // find the products for each order with their ammounts
        //    var orderInfos = new List<OrderInfo>();

        //    foreach (var order in orders)
        //    {
        //        var orderProducts = _context.OrdersProducts.Where(op => op.OrderId == order.Id).ToList();

        //        var orderInfo = new OrderInfo(order);

        //        foreach (var item in orderProducts)
        //        {
        //            var productAmmount = new ProductAmmount(_context.Products.SingleOrDefault(p => p.Id == item.ProductId));
        //            productAmmount.Ammount = item.ProductAmmount;

        //            orderInfo.ProductAmmounts.Add(productAmmount);
        //            orderInfo.OrderPrice = CountOrderPrice(order);
        //        }

        //        orderInfos.Add(orderInfo);
        //    }

        //    // prepare the model
        //    var model = new UserOrderInfoViewModel()
        //    {
        //        Orders = orderInfos,
        //        TotalPrice = CountOrdersPrice(orders)
        //    };

        //    return PartialView("_UserOrderInfo", model);
        //}

        public PartialViewResult GetUserOrderInfo(int id)
        {
            var order = _context.Orders.SingleOrDefault(o => o.Id == id);

            if (order == null)
                return PartialView("_UserOrderInfo", null);

            // find the products for this order and their ammount
            var orderInfo = new OrderInfo(order);

            var orderProducts = _context.OrdersProducts.Where(op => op.OrderId == order.Id).ToList();

            foreach (var item in orderProducts)
            {
                var productAmmount = new ProductAmmount(_context.Products.SingleOrDefault(p => p.Id == item.ProductId));
                productAmmount.Ammount = item.ProductAmmount;

                orderInfo.ProductAmmounts.Add(productAmmount);
                orderInfo.OrderPrice = CountOrderPrice(order);
            }

            return PartialView("_UserOrderInfo", orderInfo);
        }

        #region Private helpers
        private double CountOrderPrice(Order order)
        {
            double result = 0;

            foreach (var productOrder in order.OrdersProducts)
            {
                result += (productOrder.Product.Price * productOrder.ProductAmmount);
            }

            return result;
        }

        private double CountOrdersPrice(IEnumerable<Order> orders)
        {
            double totalPrice = 0;

            foreach (var order in orders)
            {
                totalPrice += CountOrderPrice(order);
            }

            return totalPrice;
        }

        private OrderFormViewModel PrepareOrderFormViewModel()
        {
            var productsAmmount = new List<ProductAmmount>();

            foreach (var product in _context.Products.ToList())
            {
                productsAmmount.Add(new ProductAmmount(product));
            }

            var viewModel = new OrderFormViewModel()
            {
                ProductsAmmount = productsAmmount
            };

            return viewModel;
        }
        #endregion
    }
}

WebStoreApp/Views/Orders/Add.cshtml
@model WebStoreApp.ViewModels.OrderFormViewModel

@{
    ViewBag.Title = "Add new order";
}

<h2>
    <label>
        New order
    </label>
</h2>

@using (Html.BeginForm("Save", "Orders"))
{
    @Html.ValidationSummary(true)

    <div class="form-group">
        <h4>
            <label class="label label-primary">
                @Html.LabelFor(m => m.DateBought)
            </label>
        </h4>
        @Html.TextBoxFor(m => m.DateBought, "{0:dd.MM.yyyy}", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.DateBought)
    </div>

    <div class="form-group">
        <h4>
            <label class="label label-primary">
                @Html.LabelFor(m => m.ProductsAmmount)
            </label>
        </h4>
        @for (int i = 0; i < Model.ProductsAmmount.Count; i++)
        {
            @Html.HiddenFor(m => m.ProductsAmmount[i].ProductId)
            @Html.Label(Model.ProductsAmmount[i].ProductName)
            @Html.TextBoxFor(m => m.ProductsAmmount[i].Ammount, new { @class = "form-control" })
        }
    </div>

    @Html.HiddenFor(m => m.Id)
    @*@Html.AntiForgeryToken()*@

    <div class="col-md-offset-1">
        <button type="submit" class="btn btn-primary">
            Create
        </button>
    </div>
}

@section scripts
{
    <script src="~/Scripts/NumberDateValidation.js"></script>
}

WebStoreApp/Views/Orders/Index.cshtml
@model IEnumerable<WebStoreApp.ViewModels.OrderViewModel>

@{
    ViewBag.Title = "Orders";
    int number = 0;
}

<div class="row text-center">
    <h2>Orders</h2>
</div>

<div class="row text-center">
    <a href="@Url.Action("Add")" class="btn btn-success">
        <span class="glyphicon glyphicon-plus"></span>
    </a>

    <a href="@Url.Action("Period")" class="btn btn-primary">
        <span class="glyphicon glyphicon-time"></span>
    </a>

    <a href="@Url.Action("UserOrder")" class="btn btn-warning">
        <span class="glyphicon glyphicon-search"></span>
    </a>
</div>
<br />
<div class="row">
    <div class="col-md-6">
        <div class="text-center">
            <h4>
                <label class="label label-primary">
                    Your orders
                </label>
            </h4>
        </div>
        <br />
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Date</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var order in Model)
                {
                    {
                        number++;
                    }

                    <tr>
                        <td class="text-center">
                            <button id="orderId" class="btn btn-default" data-order-id="@order.Id">
                                @number
                            </button>
                        </td>

                        <td class="text-center">
                            @order.Price
                        </td>

                        <td class="text-center">
                            @order.DateBought.ToString("dd.MM.yyyy")
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-md-6">
        <div id="orderInfo"></div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            $(document).on("click", "#orderId", function () {
                var orderId = $(this).attr("data-order-id");

                $.ajax({
                    url: "/Orders/GetUserOrderInfo/" + orderId,
                    method: "GET",
                    dataType: "html",
                    success: function (data) {
                        $("orderInfo").hide("fast");
                        $("#orderInfo").html(data);
                        $("#orderInfo").show("slow");
                    }
                });
            });
        });
    </script>
}

WebStoreApp/Views/Orders/Period.cshtml
@model WebStoreApp.ViewModels.PeriodViewModel

@{
    ViewBag.Title = "Period";
}

<div class="row text-center">
    <h2>
        <label>
            Periods info
        </label>
    </h2>
</div>

@using (Ajax.BeginForm("GetPeriodInfo", new AjaxOptions { UpdateTargetId = "periodInfo" }))
{
    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <div class="col-md-6">
                <div class="form-group">
                    <h4>
                        <label class="label label-primary">
                            @Html.LabelFor(m => m.StartDate)
                        </label>
                    </h4>
                    @Html.TextBoxFor(m => m.StartDate, "{0:dd.MM.yyyy}", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.StartDate)
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <h4>
                        <label class="label label-primary">
                            @Html.LabelFor(m => m.EndDate)
                        </label>
                    </h4>
                    @Html.TextBoxFor(m => m.EndDate, "{0:dd.MM.yyyy}", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.EndDate)
                </div>
            </div>
        </div>
    </div>

    <div class="row text-center">
        <button type="submit" class="btn btn-primary">Show</button>
    </div>
}
<br />
<div class="row">
    <div id="periodInfo"></div>
</div>

@section scripts
{
    <script src="~/Scripts/NumberDateValidation.js"></script>
}

WebStoreApp/Views/Orders/UserOrder.cshtml
@model WebStoreApp.ViewModels.UserOrderViewModel

@{
    ViewBag.Title = "User's order info";
}

<div class="row text-center">
    <h2>
        <label>
            User's orders
        </label>
    </h2>
</div>

@using (Ajax.BeginForm("GetUserOrderInfo", new AjaxOptions { UpdateTargetId = "userOrderInfo" }))
{
    <div class="row">
        <div class="col-md-offset-4 col-md-4 text-center">
            <div class="form-group">
                <h4>
                    <label class="label label-primary">
                        @Html.LabelFor(m => m.UserId)
                    </label>
                </h4>
                @Html.DropDownListFor(m => m.UserId, new SelectList(Model.Users, "Id", "FullName"), new { @class = "form-control width100" })
            </div>
        </div>
    </div>

    @*<div class="row">
        <div class="col-md-offset-4 col-md-4 text-center">
            <div class="form-group">
                <h4>
                    <label class="label label-primary">
                        @Html.LabelFor(m => m.UserName)
                    </label>
                </h4>
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", id = "userName" })
            </div>
        </div>
    </div>*@

    <div class="row text-center">
        <button type="submit" class="btn btn-primary">Show</button>
    </div>
}
<br />
<div class="row">
    <div id="userOrderInfo"></div>
</div>

@*@section scripts
{
    <script>
        $(document).ready(function () {
            $("#userName").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/Orders/FindUser",
                        type: "POST",
                        dataType: "json",
                        data: { Prefix: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item.FulName, value: item.FullName };
                            }))
                        }
                    });
                }
            });
        });
    </script>
}*@

WebStoreApp/Views/Orders/_PeriodInfo.cshtml
@model WebStoreApp.ViewModels.PeriodInfoViewModel

<div class="col-md-offset-4 col-md-4">
    <div class="col-md-6 text-center">
        <h4>
            <label class="label label-info">
                @Html.LabelFor(m => m.SalesNumber)
            </label>
        </h4>
        <label>
            @Model.SalesNumber
        </label>
    </div>

    <div class="col-md-6 text-center">
        <h4>
            <label class="label label-info">
                @Html.LabelFor(m => m.Price)
            </label>
        </h4>
        <label>
            @Model.Price
        </label>
    </div>
</div>

WebStoreApp/Views/Orders/_UserOrderInfo.cshtml
@model WebStoreApp.Customs.OrderInfo

<div class="col-md-offset-2 col-md-8">
    @if (Model == null)
    {
        <div class="row text-center">
            <h4>
                <label class="label label-danger">
                    The selected user doesn't have any orders
                </label>
            </h4>
        </div>
    }
    else
    {
        <div class="row text-center">
            <h4>
                <label class="label label-success">
                        Order info
                </label>
            </h4>
        </div>
        <br />
        <div class="row">
            <table class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Products</th>
                        <th>Order price</th>
                    </tr>
                </thead>

                <tbody>
                    @*@foreach (var orderInfo in Model.Orders)
                    {
                        <tr>
                            <td>
                                @orderInfo.DateBought.ToString("dd.MM.yyyy")
                            </td>

                            <td>
                                <ul class="list-group">
                                    @foreach (var product in orderInfo.ProductAmmounts)
                                    {
                                        <li class="list-group-item list-group-item-info">
                                            @product.ProductName (@product.Ammount)
                                        </li>
                                    }
                                </ul>
                            </td>

                            <td>
                                @orderInfo.OrderPrice
                            </td>
                        </tr>
                    }*@
                    <tr>
                        <td>
                            @Model.DateBought.ToString("dd.MM.yyyy")
                        </td>

                        <td>
                            <ul class="list-group">
                                @foreach (var product in Model.ProductAmmounts)
                                {
                                    <li class="list-group-item list-group-item-info">
                                        @product.ProductName (@product.Ammount)
                                    </li>
                                }
                            </ul>
                        </td>

                        <td>
                            @Model.OrderPrice
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    }
</div>